theme: jekyll-theme-minimal
logo: https://qr-official.line.me/sid/L/712korsz.png
title: LINEでかんたんワンタイムリマインダーを送れるbot Dog reminder
description: (LINEで友達とうろくしてね↑)Dog reminderはあなたをリマインド地獄から 開放します
show_downloads: false
google_analytics: UA-178643334-1
