theme: jekyll-theme-minimal
logo: https://qr-official.line.me/sid/L/712korsz.png
title: LINEでかんたんワンタイムリマインダーを送れるbot Dog reminder
description: Dog reminderはあなたをリマインド地獄から 開放します LINEでともだちとうろくしてね
show_downloads: false
