theme: jekyll-theme-minimal
logo: https://qr-official.line.me/sid/L/712korsz.png
title: LINEで友達登録してみてね↓
description: Dog reminderはあなたをリマインド地獄から 開放します
show_downloads: false
google_analytics: UA-178643334-1
